podTemplate(
    label: 'cd-jenkins-jenkins-slave', 
    containers: [ 
        containerTemplate(
            name: 'docker', 
            image: 'docker:18.02',
            ttyEnabled: true,
            command: 'cat'
        ),
    ],
    volumes: [
        hostPathVolume(
            hostPath: '/var/run/docker.sock',
            mountPath: '/var/run/docker.sock'
        )
    ]
) {
    node('cd-jenkins-jenkins-slave') {
        def commitId
        stage ('Checkout') {
            checkout scm
            commitId = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        }
        def repository
        def projectId = 'basic-k8s'
    
        stage ('Build') {
            container ('docker') {
                repository = "gcr.io/${projectId}/questionnaire"
 
                docker.withRegistry('https://gcr.io', "gcr-${projectId}") {
                     def dockerImage = docker.build("${projectId}/questionnaire:${commitId}", ".")
                    
                    dockerImage.push('latest')
                }
            }
        }
    }
}