podTemplate(
    label: 'cd-jenkins-jenkins-slave', 
    containers: [ 
        containerTemplate(
            name: 'docker', 
            image: 'docker:18.02',
            ttyEnabled: true,
            command: 'cat'
        ),
        containerTemplate(
            name: 'kubectl', 
            image: 'gcr.io/cloud-builders/kubectl',
            ttyEnabled: true,
            command: 'cat'
        ),
    ],
    volumes: [
        hostPathVolume(
            hostPath: '/var/run/docker.sock',
            mountPath: '/var/run/docker.sock'
        )
    ]
) {
    node('cd-jenkins-jenkins-slave') {
        def commitId
        stage ('Checkout') {
            checkout scm
            commitId = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        }
        def projectId = 'basic-k8s'
    
        stage ('Build') {
            container ('docker') {
                def dockerImage = docker.build("${projectId}/questionnaire", "./microservices/questionnaire")
                
                docker.withRegistry('https://gcr.io', "gcr:${projectId}") {
                    
                    dockerImage.push('latest')
                }
            }
        }
        
        stage ('Deployment') {
            container ('kubectl') {
                 docker.withRegistry('https://gcr.io', "gcr:${projectId}") {
                    
                  sh("kubectl --namespace=defult apply -f ./microservices/questionnaire/questionnaire-service.yaml")
                }
            }
        }
    }
}