apiVersion: v1
kind: Service
metadata:
  name: questionnaire-service
spec:
  selector:
    app: questionnaire-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionnaire-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire-service
  template:
    metadata:
      labels:
        app: questionnaire-service
    spec:
      containers:
        - name: questionnaire-service
          image: gcr.io/basic-k8s/questionnaire
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: db-url
          imagePullPolicy: Always
